#!/bin/bash

_t3tool() {
    local cur;
    COMPREPLY=();
    cur="${COMP_WORDS[COMP_CWORD]}";
    t=$( t3tool _complete "$cur" "$COMP_LINE" );
    if [ "$t" == "_path" ]; then
        COMPREPLY=( $( compgen -o plusdirs -f -- $cur ) );
    else
        COMPREPLY=( $( compgen -W "$t" -- $cur ) );
    fi
    return 0
}

complete -o filenames -F _t3tool t3tool


