#!/bin/bash

_t3tool() {
    local cur;
    COMPREPLY=();
    cur="${COMP_WORDS[COMP_CWORD]}";
    t=$( t3tool _complete "$cur" "$COMP_LINE" );
    COMPREPLY=( $( compgen -W "$t" -- $cur ) );
    return 0
}

complete -F _t3tool t3tool


